services:
  test:
    container_name: hives-test
    image: hives-backend:test
    build:
      context: .
      target: test
      dockerfile: ./Dockerfile
    volumes:
      - ./coverage:/test/coverage

  prod:
    networks:
      - hives-network
      - traefik-network
    depends_on:
      db:
        condition: service_healthy
    container_name: hives-backend
    image: hives-backend:prod
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile
    environment:
      JWT: "${JWT}"
      REFRESH: "${REFRESH}"
      DATABASE_URL: "${DATABASE_URL}"
      PORT: "${PORT}"
      EMAIL: "${EMAIL}"
      CLIENT_ID_MAIL: "${CLIENT_ID_MAIL}"
      CLIENT_SECRET_MAIL: "${CLIENT_SECRET_MAIL}"
      REFRESH_TOKEN_MAIL: "${REFRESH_TOKEN_MAIL}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.hivesapp.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  db:
    image: mariadb:lts
    container_name: hives-db
    restart: unless-stopped
    networks:
      - hives-network
      - db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    volumes:
      - hives-volumes:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  hives-volumes:

networks:
  hives-network:
  traefik-network:
    external: true
  db:
    external: true
