version: "3.9"
services:
  dev:
    container_name: hives-backend-dev
    image: hives-backend:dev
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    networks:
      - hives-network
    volumes:
      - .:/develop
    depends_on:
      - phpmyadmin
    ports:
      - 3000:3000
      - 9229:9229
    tty: true

  prod:
    networks:
      - hives-network
      - traefik-network
    depends_on:
      - db
    container_name: hives-backend
    image: hives-backend:prod
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile
    environment:
      - JWT=${JWT}
      - REFRESH=${REFRESH}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - EMAIL=${EMAIL}
      - CLIENT_ID_MAIL=${CLIENT_ID_MAIL}
      - CLIENT_SECRET_MAIL=${CLIENT_SECRET_MAIL}
      - REFRESH_TOKEN_MAIL=${REFRESH_TOKEN_MAIL}      
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.hivesapp.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      
  db:
    image: mariadb:lts
    restart: always
    networks:
      - hives-network
      - db
    environment:
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - hives-volumes:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    networks:
      - hives-network
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

volumes:
  hives-volumes:


networks:
  hives-network:
  traefik-network:
    external: true
  db:
    external: true