version: '3'
services:
  dev:
    container_name: hives-backend-dev
    image: hives-backend:dev
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    networks:
      - hives-network
    volumes:
      - .:/develop
    depends_on:
      - phpmyadmin
    ports:
      - 3000:3000
      - 9229:9229
    tty: true

  test:
    container_name: hives-test
    image: hives-backend:test
    build:
      context: .
      target: test
      dockerfile: ./Dockerfile
    volumes:
      - ./coverage:/test/coverage

  prod:
    networks:
      - hives-network
      - traefik-network
    depends_on:
      db:
        condition: service_healthy
    container_name: hives-backend
    image: hives-backend:prod
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile
    environment:
      - JWT=${JWT}
      - REFRESH=${REFRESH}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - EMAIL=${EMAIL}
      - CLIENT_ID_MAIL=${CLIENT_ID_MAIL}
      - CLIENT_SECRET_MAIL=${CLIENT_SECRET_MAIL}
      - REFRESH_TOKEN_MAIL=${REFRESH_TOKEN_MAIL}
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.hivesapp.fr`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls.certresolver=myresolver'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  migration:
    container_name: hives-migration
    image: hives-backend:migration
    build:
      context: .
      target: migration
      dockerfile: ./Dockerfile
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: mariadb:lts
    restart: always
    networks:
      - hives-network
      - db
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - hives-volumes:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    depends_on:
      - db
    networks:
      - hives-network
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

volumes:
  hives-volumes:

networks:
  hives-network:
  traefik-network:
    external: true
  db:
    external: true
