services:
  app:
    build: 
      context: .
      target: dev
      dockerfile: ../Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:lts
    restart: unless-stopped
    networks:
      - hives-network
    volumes:
      - hives-dev-data:/var/lib/postgresql/data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_PASSWORD: '123'
      MARIADB_USER: 'docker'
      MARIADB_DATABASE: 'hivesbdd'

  phpmyadmin:
    networks:
      - hives-network
    image: phpmyadmin:latest
    ports:
      - 8080:80

volumes:
  hives-dev-data:

networks:
  hives-network:
