name: develop

on:
  push:
    branches:
    - feature/separation_migration
  
jobs:        
    
  develop:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy repository
      uses: actions/checkout@v4

    - name: 'Create env file'
      run: |
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_DEV }} > .env

    - name: 'Run migration'
      run: |
        docker build -t hivesapi:migration --target migration .
        docker run --env-file .env hivesapi:migration

    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_NAME }}
        docker_options: "--no-cache --target prod"