name: main

on:
  push:
    branches:
    - main
  
jobs:        
    
  main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy repository
      uses: actions/checkout@v4

    - name: 'Create env file'
      run: |
        touch .env
        echo MARIADB_ROOT_PASSWORD=${{ secrets.MARIADB_ROOT_PASSWORD }} >> .env
        echo MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }} > .env
        echo PORT=3000 >> .env
        echo JWT=${{ secrets.JWT }} >> .env
        echo REFRESH=${{ secrets.REFRESH }} >> .env
        echo DATABASE_URL=${{ secrets.MARIADB }} >> .env
        echo EMAIL=${{ secrets.EMAIL }} >> .env
        echo CLIENT_ID_MAIL=${{ secrets.CLIENT_ID_MAIL }} >> .env
        echo CLIENT_SECRET_MAIL=${{ secrets.CLIENT_SECRET_MAIL }} >> .env
        echo REFRESH_TOKEN_MAIL=${{ secrets.REFRESH_TOKEN_MAIL }} >> .env
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env

    - name: Copy file via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        rm: true
        source: "."
        target: api

    - name: deploy api
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker compose -f api/docker-compose.yml up --build migration
          sudo docker rm hives-migration
          sudo docker image rm hives-backend:migration
          sudo docker compose -f api/docker-compose.yml up --build -d prod